CREATE TABLE IF NOT EXISTS roles (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS users (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    CPF CHAR(11) NOT NULL UNIQUE,
    NAME VARCHAR(128) NOT NULL,
    USER_NAME VARCHAR(64) NOT NULL UNIQUE,
    PASS VARCHAR(72) NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY INT,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY INT,
    DELETED_AT TIMESTAMP,
    DELETED_BY INT,
    CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
    CONSTRAINT FK_USERS_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
    CONSTRAINT FK_USERS_UPDATER FOREIGN KEY (UPDATED_BY) REFERENCES USERS (ID),
    CONSTRAINT FK_USERS_DELETER FOREIGN KEY (DELETED_BY) REFERENCES USERS (ID)
);

ALTER TABLE roles
    ADD COLUMN
        permissions JSON DEFAULT (json_object());

ALTER TABLE roles
    ADD COLUMN DELETED_AT TIMESTAMP,
    ADD COLUMN DELETED_BY INT;
