CREATE TABLE IF NOT EXISTS arrecadacoes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_ARRECADACAO DATE NOT NULL,
    TIPO_ARRECADACAO VARCHAR(80) NOT NULL DEFAULT 'Doação em dinheiro',
    DESCRICAO VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);