CREATE TABLE beneficiaries (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(144) NOT NULL,
    GENDER CHAR(1) DEFAULT 'O',
    NATIONAL_ID CHAR(11) NOT NULL UNIQUE,
    PHONE CHAR(11) NOT NULL,
    STREET VARCHAR(144) NOT NULL,
    HOUSE_NUMBER INT NOT NULL,
    COMPLEMENT VARCHAR(32),
    NEIGHBORHOOD VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) DEFAULT "SÃO PAULO",
    CITY VARCHAR(32) DEFAULT "PRESIDENTE PRUDENTE"
);

ALTER TABLE beneficiaries 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;
