CREATE TABLE BILLS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DUE_DATE TIMESTAMP NOT NULL,
    VALUE DECIMAL(10, 2) NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY INT NOT NULL,

    EXTENDED_AT TIMESTAMP,
    EXTENDED_BY INT,

    PAID_AT TIMESTAMP,
    PAID_BY INT,

    CANCELED_AT TIMESTAMP,
    CANCELED_BY INT,

    CONSTRAINT FK_BILLS_CREATOR
        FOREIGN KEY (CREATED_BY)
            REFERENCES users(ID),

    CONSTRAINT FK_BILLS_EXTENDER
        FOREIGN KEY (EXTENDED_BY)
            REFERENCES users(ID),

    CONSTRAINT FK_BILLS_PAYER
        FOREIGN KEY (PAID_BY)
            REFERENCES users(ID),

    CONSTRAINT FK_BILL_CANCELER
        FOREIGN KEY (CANCELED_BY)
            REFERENCES users(ID)
);

ALTER TABLE bills ADD COLUMN EXTENDED_FROM TIMESTAMP;
ALTER TABLE bills ADD COLUMN EXTENDED_DETAILS VARCHAR(256);
ALTER TABLE bills ADD COLUMN CANCELATION_DETAILS VARCHAR(256);