CREATE TABLE cities (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL
);

INSERT INTO cities (NAME)
    VALUES ("Presidente Prudente");

ALTER TABLE cities 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

ALTER TABLE cities
    ADD COLUMN STATE CHAR(2) NOT NULL;

UPDATE cities
    SET STATE="SP"
    WHERE ID = 1;
