CREATE TABLE families (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DELETED_AT TIMESTAMP
);

CREATE TABLE family_participants (
    BEN_ID INT NOT NULL,
    FAM_ID INT NOT NULL,
    IS_RESPOSIBLE TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT PK_FAMILY_PARTICIPANTS PRIMARY KEY (BEN_ID, FAM_ID),
    CONSTRAINT FK_FAMILY_PARTICIPANTS_BENEFICIARIES FOREIGN KEY (BEN_ID) REFERENCES beneficiaries (ID),
    CONSTRAINT FK_FAMILY_PARTICIPANTS_FAMILIES FOREIGN KEY (FAM_ID) REFERENCES families (ID)
);
