CREATE TABLE measuring_units (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    SYMBOL VARCHAR(8) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DELETED_AT TIMESTAMP
);

INSERT INTO measuring_units 
	(name, symbol)
VALUES
	("Quilograma", "kg"),
	("Litro", "l"),
	("Unidade", "un");
