CREATE TABLE IF NOT EXISTS products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);

ALTER TABLE products DROP COLUMN PRICE;
ALTER TABLE products DROP COLUMN STOCK;

ALTER TABLE products ADD COLUMN MEASURING_UNIT_ID INT NOT NULL;
ALTER TABLE products ADD CONSTRAINT FK_products_MEASURING_UNITS 
    FOREIGN KEY (MEASURING_UNIT_ID) REFERENCES measuring_units(ID);

ALTER TABLE products ADD NEEDS_REFRIGERATION TINYINT DEFAULT 0;
ALTER TABLE products ADD IS_PERISHABLE TINYINT DEFAULT 0;

ALTER TABLE products ADD COLUMN DELETED_AT DATETIME NULL;
ALTER TABLE products ADD COLUMN UPDATED_AT DATETIME NULL;
ALTER TABLE products ADD COLUMN CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products ADD COLUMN DESCRIPTION VARCHAR(140);