CREATE TABLE IF NOT EXISTS PRODUCTS (

    ID INT AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(120) NOT NULL,

    DESCRIPTION TEXT,

    PRICE DECIMAL(10,2) NOT NULL,

    STOCK INT NOT NULL,

    STATUS VARCHAR(20) DEFAULT 'ACTIVE'

);