CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);

ALTER TABLE PRODUCTS DROP COLUMN PRICE;
ALTER TABLE PRODUCTS DROP COLUMN STOCK;

ALTER TABLE PRODUCTS ADD COLUMN MEASURING_UNIT_ID INT NOT NULL;
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_MEASURING_UNITS FOREIGN KEY (MEASURING_UNIT_ID) REFERENCES MEASURING_UNITS(ID);

ALTER TABLE PRODUCTS ADD NEEDS_REFRIGERATION TINYINT DEFAULT 0;
ALTER TABLE PRODUCTS ADD IS_PERISHABLE TINYINT DEFAULT 0;

ALTER TABLE PRODUCTS ADD COLUMN DELETED_AT DATETIME NULL;
ALTER TABLE PRODUCTS ADD COLUMN UPDATED_AT DATETIME NULL;
ALTER TABLE PRODUCTS ADD COLUMN CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PRODUCTS ADD COLUMN DESCRIPTION VARCHAR(140);