/** @type {import("./BeneficiariesService").Beneficiary[]} */
export const BENEFICIARIES_MOCK = [
  {
    nationalId: "241.236.019-79",
    name: "Isabel Isis Bernardes",
    hasOpenRequest: true,
    street: "Rua Cardeal Amarelo",
    neighborhood: "Suru",
    number: 152,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "f",
    phone: "(18) 98772-1119",
  },
  {
    nationalId: "051.161.292-33",
    name: "Julio Juan de Paula",
    hasOpenRequest: true,
    street: "Beco da Cerca",
    neighborhood: "Charnequinha",
    number: 996,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 99728-5952",
  },
  {
    nationalId: "770.129.294-21",
    name: "Marcos Vinicius Cláudio Victor Freitas",
    hasOpenRequest: true,
    street: "Rua São Pedro",
    neighborhood: "Zumbi dos Palmares",
    number: 794,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 99780-8657",
  },
  {
    nationalId: "629.674.515-09",
    name: "Julia Mariana Lopes",
    hasOpenRequest: false,
    street: "Avenida Calama",
    neighborhood: "Planalto",
    number: 117,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "f",
    phone: "(18) 98156-8035",
  },
  {
    nationalId: "349.292.802-14",
    name: "Ryan Diego Guilherme Ramos",
    hasOpenRequest: false,
    street: "Rua Inês Santos",
    neighborhood: "Canto da Varzea",
    number: 669,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 98193-5759",
  },
  {
    nationalId: "140.476.001-64",
    name: "Nelson Eduardo Rafael Moreira",
    hasOpenRequest: true,
    street: "Travessa Suissa II",
    neighborhood: "Zona de Expansão (Robalo)",
    number: 817,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 99806-3822",
  },
  {
    nationalId: "428.706.224-81",
    name: "Gabriela Emilly Stefany Mendes",
    hasOpenRequest: true,
    street: "Rua B",
    neighborhood: "Nova Matinha",
    number: 446,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "f",
    phone: "(18) 98890-0652",
  },
  {
    nationalId: "314.832.932-54",
    name: "Lucas Enrico Nathan Almeida",
    hasOpenRequest: false,
    street: "Rua Doutor Amaurício D'ávila",
    neighborhood: "Mário Andreazza",
    number: 420,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 99189-5526",
  },
  {
    nationalId: "746.837.251-93",
    name: "Jaqueline Isabela Liz Martins",
    hasOpenRequest: false,
    street: "Travessa Marcílio Dias",
    neighborhood: "Vila Lira",
    number: 811,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "f",
    phone: "(18) 98371-2096",
  },
  {
    nationalId: "491.344.599-52",
    name: "Renan Renan Márcio da Mota",
    hasOpenRequest: false,
    street: "Rua Vinte e Quatro",
    neighborhood: "Vila Sion",
    number: 211,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 98931-0494",
  },
  {
    nationalId: "871.100.626-94",
    name: "Enrico Henry Lorenzo da Rocha",
    hasOpenRequest: false,
    street: "Rua Vinte e Sete de Maio",
    neighborhood: "Aroeiras",
    number: 779,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 99225-0283",
  },
  {
    nationalId: "468.412.465-78",
    name: "Benjamin José Theo Barros",
    hasOpenRequest: false,
    street: "Rua Galileu Guedes de Oliveira",
    neighborhood: "Santos Dumont",
    number: 925,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "m",
    phone: "(18) 98897-0268",
  },
  {
    nationalId: "803.016.236-78",
    name: "Mariana Joana Almeida",
    hasOpenRequest: true,
    street: "Avenida Marechal Deodoro",
    neighborhood: "Cidade Nova",
    number: 992,
    complement: "",
    city: "1",
    state: "sp",
    family: "",
    gender: "f",
    phone: "(18) 99276-1711",
  },
];
