CREATE TABLE cities (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP NULL DEFAULT NULL,
  STATE CHAR(2) NOT NULL
);

INSERT INTO cities (name, state)
VALUES ("Presidente Prudente", "SP");
